/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restoro.Interfaces;
import restoro.Controllers.CheckAdmin;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author omrmh
 */
public class CheckRestaurantUI extends javax.swing.JFrame {
   private JTextField adminIdField;
    private JTextField restaurantIdField;
    private JButton checkButton;
    private JTextArea outputArea;

        private final CheckAdmin checkAdmin = new CheckAdmin();

    
    /**
     * Creates new form CheckRestaurantUI
     */
    public CheckRestaurantUI() {
        
         setTitle("Check Restaurant Availability");
        setSize(400, 300);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(null);

        JLabel adminIdLabel = new JLabel("Admin ID:");
        adminIdLabel.setBounds(20, 20, 100, 25);
        add(adminIdLabel);

        adminIdField = new JTextField();
        adminIdField.setBounds(130, 20, 200, 25);
        add(adminIdField);

        JLabel restaurantIdLabel = new JLabel("Restaurant ID:");
        restaurantIdLabel.setBounds(20, 60, 100, 25);
        add(restaurantIdLabel);

        restaurantIdField = new JTextField();
        restaurantIdField.setBounds(130, 60, 200, 25);
        add(restaurantIdField);

        checkButton = new JButton("Check Availability");
        checkButton.setBounds(100, 100, 180, 30);
        add(checkButton);

        outputArea = new JTextArea();
        outputArea.setBounds(20, 150, 340, 100);
        outputArea.setEditable(false);
        add(outputArea);

        checkButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int adminId = Integer.parseInt(adminIdField.getText());
                int restaurantId = Integer.parseInt(restaurantIdField.getText());
                outputArea.setText(""); // clear output

                if (checkAdmin.verifyAccess(adminId)) {
                    outputArea.append("Access Granted\n");
                    checkAdmin.selectRestaurant(adminId, restaurantId, outputArea);
                } else {
                    outputArea.append("Access Denied\n");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckRestaurantUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckRestaurantUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckRestaurantUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckRestaurantUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckRestaurantUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
