/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restoro.Interfaces;
import restoro.Controllers.CustomerOrderController;
import restoro.Entities.Restaurant;
import restoro.Entities.Order;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.List;

/**
 *
 * @author user
 */
public class CustomerUI extends javax.swing.JFrame {

    /**
     * Creates new form CustomerUI
     */
    private CustomerOrderController controller = new CustomerOrderController();
    private int customerId;

    private DefaultListModel<String> listModel = new DefaultListModel<>();
    private JList<String> orderList = new JList<>(listModel);
    private JTextArea detailsArea = new JTextArea();

    private JButton reorderButton = new JButton("Reorder");
    
    public CustomerUI() {
         setTitle("Customer Order History");
        setSize(500, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        detailsArea.setEditable(false);

        // Order selection listener
        orderList.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                showOrderDetails();
            }
        });

        reorderButton.addActionListener(e -> reorderSelectedOrder());

        add(new JScrollPane(orderList), BorderLayout.CENTER);
        add(new JScrollPane(detailsArea), BorderLayout.EAST);
        add(reorderButton, BorderLayout.SOUTH);
    }
    public void login(String email, String password) {
        if (email.equals("customer@example.com") && password.equals("abcd")) {
            customerId = 1001;
            JOptionPane.showMessageDialog(this, "Login Success");
            showPastOrders();
        } else {
            JOptionPane.showMessageDialog(this, "Login Failed");
            System.exit(0);
        }
    }

    private void showPastOrders() {
        List<Order> orders = controller.getPastOrders(customerId);
        listModel.clear();

        if (orders.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No Past Orders");
            return;
        }

        for (Order order : orders) {
            listModel.addElement("Order ID: " + order.getOrderId());
        }
    }

    private void showOrderDetails() {
        int selectedIndex = orderList.getSelectedIndex();
        if (selectedIndex != -1) {
            String selectedValue = listModel.get(selectedIndex);
            int orderId = Integer.parseInt(selectedValue.replaceAll("\\D+", ""));

            Order selectedOrder = controller.viewOrderDetails(orderId);
            if (selectedOrder != null) {
                Restaurant res = controller.getRestaurantDetails(selectedOrder.getRestaurantId());

                detailsArea.setText("Order Details:\n" + selectedOrder.getOrderDetails()
                        + "\n\nRestaurant:\n" + res.getDetails());
            }
        }
    }

    private void reorderSelectedOrder() {
        int selectedIndex = orderList.getSelectedIndex();
        if (selectedIndex != -1) {
            String selectedValue = listModel.get(selectedIndex);
            int orderId = Integer.parseInt(selectedValue.replaceAll("\\D+", ""));

            controller.reorderOrder(orderId);
            JOptionPane.showMessageDialog(this, "Order " + orderId + " has been reordered!");
        } else {
            JOptionPane.showMessageDialog(this, "Please select an order first.");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
