/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restoro.Interfaces;

import java.util.ArrayList;
import restoro.Entities.Customer;
import restoro.Entities.MenuItem;
import restoro.Entities.Restaurant;

/**
 *
 * @author omrmh
 */
public class ViewMenuUI extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenuUI
     */
    Customer customer;
    Restaurant restaurant;
    ArrayList<MenuItem> menuItems;
    MenuItem item;
    boolean found = false;
    public ViewMenuUI(Customer customer,Restaurant restaurant) {
        initComponents();
        this.customer = customer;
        this.restaurant = restaurant;
        menuItems = restaurant.getMenu().viewAllItems();
        Order1.setText(menuItems.get(0).toString());
        Order2.setText(menuItems.get(1).toString());
        Order3.setText(menuItems.get(2).toString());
    }

    private ViewMenuUI() {
        initComponents();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Order3 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Order1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Order2 = new javax.swing.JTextArea();
        ChooseOrder1 = new javax.swing.JButton();
        ChooseOrder2 = new javax.swing.JButton();
        ChooseOrder3 = new javax.swing.JButton();
        SearchInput = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        Procced = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Order3.setColumns(20);
        Order3.setRows(5);
        jScrollPane2.setViewportView(Order3);

        Order1.setColumns(20);
        Order1.setRows(5);
        jScrollPane3.setViewportView(Order1);

        Order2.setColumns(20);
        Order2.setRows(5);
        jScrollPane4.setViewportView(Order2);

        ChooseOrder1.setText("jButton1");
        ChooseOrder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseOrder1ActionPerformed(evt);
            }
        });

        ChooseOrder2.setText("jButton2");
        ChooseOrder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseOrder2ActionPerformed(evt);
            }
        });

        ChooseOrder3.setText("jButton3");
        ChooseOrder3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseOrder3ActionPerformed(evt);
            }
        });

        SearchInput.setText("jTextField1");

        Search.setText("jButton1");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Procced.setText("jButton1");
        Procced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProccedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ChooseOrder3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(ChooseOrder2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Procced))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SearchInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChooseOrder1)
                            .addComponent(Search))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SearchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Search))
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(ChooseOrder1)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ChooseOrder2)
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ChooseOrder3)
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Procced)
                                .addContainerGap())))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChooseOrder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseOrder1ActionPerformed
        // TODO add your handling code here:
        if (found){
            customer.addToCart(item);            
        }
        else{
            customer.addToCart(menuItems.get(0));            
        }

    }//GEN-LAST:event_ChooseOrder1ActionPerformed

    private void ChooseOrder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseOrder2ActionPerformed
        // TODO add your handling code here:
                customer.addToCart(menuItems.get(1));
    }//GEN-LAST:event_ChooseOrder2ActionPerformed

    private void ChooseOrder3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseOrder3ActionPerformed
        // TODO add your handling code here:
                customer.addToCart(menuItems.get(2));
    }//GEN-LAST:event_ChooseOrder3ActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        String query = SearchInput.getText();
        item = restaurant.getMenu().searchItem(query);
        if (item != null){
            Order1.setText(item.toString());
            found =true;
        }
        
        
    }//GEN-LAST:event_SearchActionPerformed

    private void ProccedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProccedActionPerformed
        // TODO add your handling code here:
              ViewCartUI vc = new ViewCartUI(customer);
        vc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProccedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenuUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChooseOrder1;
    private javax.swing.JButton ChooseOrder2;
    private javax.swing.JButton ChooseOrder3;
    private javax.swing.JTextArea Order1;
    private javax.swing.JTextArea Order2;
    private javax.swing.JTextArea Order3;
    private javax.swing.JButton Procced;
    private javax.swing.JButton Search;
    private javax.swing.JTextField SearchInput;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
