/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restoro.Interfaces;

import java.util.ArrayList;
import restoro.Entities.Delivery;
import restoro.Entities.Order;
import restoro.Entities.Restaurant;

/**
 *
 * @author omrmh
 */
public class ViewAssignedOrderUI extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenuUI
     */
    Delivery delivery;
    Restaurant restaurant;
    ArrayList<Order> orders;
    
    public ViewAssignedOrderUI(Delivery delivery) {
        initComponents();     
        this.delivery = delivery;
        
        orders = delivery.getAssignedOrders(delivery);
        Order1.setText(orders.get(0).toString());
        Order1.setText(orders.get(1).toString());
        Order1.setText(orders.get(2).toString());
    }

    private ViewAssignedOrderUI() {
        initComponents();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Order3 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        Order1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Order2 = new javax.swing.JTextArea();
        ChooseItem1 = new javax.swing.JButton();
        ChooseItem2 = new javax.swing.JButton();
        ChooseItem3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Order3.setColumns(20);
        Order3.setRows(5);
        jScrollPane2.setViewportView(Order3);

        Order1.setColumns(20);
        Order1.setRows(5);
        jScrollPane3.setViewportView(Order1);

        Order2.setColumns(20);
        Order2.setRows(5);
        jScrollPane4.setViewportView(Order2);

        ChooseItem1.setText("jButton1");
        ChooseItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseItem1ActionPerformed(evt);
            }
        });

        ChooseItem2.setText("jButton2");
        ChooseItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseItem2ActionPerformed(evt);
            }
        });

        ChooseItem3.setText("jButton3");
        ChooseItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseItem3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(ChooseItem1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(ChooseItem2)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(9, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ChooseItem3)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChooseItem1)
                    .addComponent(ChooseItem2)
                    .addComponent(ChooseItem3))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChooseItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseItem1ActionPerformed
        // TODO add your handling code here:
        
        new UpdateDeliveryStatusUI(orders.get(0)).setVisible(true);

    }//GEN-LAST:event_ChooseItem1ActionPerformed

    private void ChooseItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseItem2ActionPerformed
        // TODO add your handling code here:
        new UpdateDeliveryStatusUI(orders.get(1)).setVisible(true);
    }//GEN-LAST:event_ChooseItem2ActionPerformed

    private void ChooseItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseItem3ActionPerformed
        // TODO add your handling code here:
        new UpdateDeliveryStatusUI(orders.get(2)).setVisible(true);
    }//GEN-LAST:event_ChooseItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAssignedOrderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAssignedOrderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAssignedOrderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAssignedOrderUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAssignedOrderUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChooseItem1;
    private javax.swing.JButton ChooseItem2;
    private javax.swing.JButton ChooseItem3;
    private javax.swing.JTextArea Order1;
    private javax.swing.JTextArea Order2;
    private javax.swing.JTextArea Order3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
