/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restoro;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.List;
/**
 *
 * @author user
 */
public class DeliveryStaffUI extends javax.swing.JFrame {
    private DeliveryController controller = new DeliveryController();
    private int staffId;
    private DefaultListModel<String> listModel = new DefaultListModel<>();
    private JList<String> orderList;
    private JTextArea detailsArea;
    /**
     * Creates new form DeliveryStaffUI
     */
    public DeliveryStaffUI() {
         setTitle("Delivery Staff UI");
        setSize(400, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        orderList = new JList<>(listModel);
        JScrollPane scrollPane = new JScrollPane(orderList);
        detailsArea = new JTextArea();
        detailsArea.setEditable(false);

        JButton viewDetailsButton = new JButton("View Order Details");

        viewDetailsButton.addActionListener(e -> showOrderDetails());

        add(scrollPane, BorderLayout.CENTER);
        add(viewDetailsButton, BorderLayout.SOUTH);
        add(detailsArea, BorderLayout.EAST);
    }
    
    public void login(String email, String password) {
        if (email.equals("staff@example.com") && password.equals("1234")) {
            staffId = 101;
            JOptionPane.showMessageDialog(this, "Login Success");
            showAssignedOrders();
        } else {
            JOptionPane.showMessageDialog(this, "Login Failed");
            System.exit(0);
        }
    }

    private void showAssignedOrders() {
        List<Order> orders = controller.getAssignedOrders(staffId);
        listModel.clear();

        if (orders.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No Assigned Orders");
            return;
        }

        for (Order order : orders) {
            listModel.addElement("Order ID: " + order.getOrderId());
        }
    }
     private void showOrderDetails() {
        int selectedIndex = orderList.getSelectedIndex();
        if (selectedIndex != -1) {
            String selectedValue = listModel.get(selectedIndex);
            int orderId = Integer.parseInt(selectedValue.replaceAll("\\D+", ""));
            Order selectedOrder = controller.viewOrderDetails(orderId, staffId);
            if (selectedOrder != null) {
                Restaurant restaurant = controller.getRestaurantDetails(selectedOrder.getRestaurantId());
                detailsArea.setText("Order Details:\n" + selectedOrder.getOrderDetails()
                        + "\n\nRestaurant Info:\n" + restaurant.getDetails());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select an order first.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   public static void main(String[] args) {
        DeliveryStaffUI frame = new DeliveryStaffUI();
        frame.setVisible(true);
        frame.login("staff@example.com", "1234"); // You can later add a proper login form
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
